/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Tue Feb 23 15:33:07 2016. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Simple_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Simple, lucky_number, lucky_number, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Simple, message, lucky_number, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
