/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Tue Mar  1 10:25:40 2016. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PrinterStatus_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PrinterStatus, targetHeightMicrometer, targetHeightMicrometer, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PrinterStatus, currentHeightMicrometer, targetHeightMicrometer, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, PrinterStatus, waitingForNextLayerHeight, currentHeightMicrometer, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, PrinterStatus, status, waitingForNextLayerHeight, 0),
    PB_LAST_FIELD
};

const pb_field_t DripRecorded_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DripRecorded, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t SetDripCount_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetDripCount, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t MoveToDripCount_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MoveToDripCount, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t SetCurrentHeight_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetCurrentHeight, heightMicrometers, heightMicrometers, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
