/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Tue Mar  1 10:25:40 2016. */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _PrinterStatus_Status {
    PrinterStatus_Status_NEW = 0,
    PrinterStatus_Status_PRINTING = 1,
    PrinterStatus_Status_WAITING = 2,
    PrinterStatus_Status_COMPLETE = 3
} PrinterStatus_Status;

/* Struct definitions */
typedef struct _DripRecorded {
    uint32_t drips;
/* @@protoc_insertion_point(struct:DripRecorded) */
} DripRecorded;

typedef struct _MoveToDripCount {
    uint32_t drips;
/* @@protoc_insertion_point(struct:MoveToDripCount) */
} MoveToDripCount;

typedef struct _PrinterStatus {
    uint32_t targetHeightMicrometer;
    uint32_t currentHeightMicrometer;
    bool waitingForNextLayerHeight;
    PrinterStatus_Status status;
/* @@protoc_insertion_point(struct:PrinterStatus) */
} PrinterStatus;

typedef struct _SetCurrentHeight {
    uint32_t heightMicrometers;
/* @@protoc_insertion_point(struct:SetCurrentHeight) */
} SetCurrentHeight;

typedef struct _SetDripCount {
    uint32_t drips;
/* @@protoc_insertion_point(struct:SetDripCount) */
} SetDripCount;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PrinterStatus_init_default               {0, 0, 0, (PrinterStatus_Status)0}
#define DripRecorded_init_default                {0}
#define SetDripCount_init_default                {0}
#define MoveToDripCount_init_default             {0}
#define SetCurrentHeight_init_default            {0}
#define PrinterStatus_init_zero                  {0, 0, 0, (PrinterStatus_Status)0}
#define DripRecorded_init_zero                   {0}
#define SetDripCount_init_zero                   {0}
#define MoveToDripCount_init_zero                {0}
#define SetCurrentHeight_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define DripRecorded_drips_tag                   1
#define MoveToDripCount_drips_tag                1
#define PrinterStatus_targetHeightMicrometer_tag 1
#define PrinterStatus_currentHeightMicrometer_tag 2
#define PrinterStatus_waitingForNextLayerHeight_tag 3
#define PrinterStatus_status_tag                 4
#define SetCurrentHeight_heightMicrometers_tag   1
#define SetDripCount_drips_tag                   1

/* Struct field encoding specification for nanopb */
extern const pb_field_t PrinterStatus_fields[5];
extern const pb_field_t DripRecorded_fields[2];
extern const pb_field_t SetDripCount_fields[2];
extern const pb_field_t MoveToDripCount_fields[2];
extern const pb_field_t SetCurrentHeight_fields[2];

/* Maximum encoded size of messages (where known) */
#define PrinterStatus_size                       16
#define DripRecorded_size                        6
#define SetDripCount_size                        6
#define MoveToDripCount_size                     6
#define SetCurrentHeight_size                    6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
