all:
	g++ -D _TEST_FLAGGER PeachyFlagger.cpp -o testFlagger
	g++ -D _TEST_PEACHYSTEPPER PeachyStepper.cpp -o testStepper
flagger:
	g++ -D _TEST_FLAGGER PeachyFlagger.cpp -o testFlagger
stepper:
	g++ -D _TEST_PEACHYSTEPPER PeachyStepper.cpp -o testStepper
