all:
	g++ -D _TEST_FLAGGER Flagger.cpp -o testFlag
	g++ -D _TEST_PEACHYSTEPPER PeachyStepper.cpp -o testStepper
flagger:
	g++ -D _TEST_FLAGGER Flagger.cpp -o testFlag
stepper:
	g++ -D _TEST_PEACHYSTEPPER PeachyStepper.cpp -o testStepper
